Revert "Make CHANGE_APP_IDLE_STATE a system API"
This reverts commit 235cca4a8140f92c4e22e79703e6c326a6ee8207.

Fails on walleye with:

java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions whitelist: {com.android.settings: android.permission.CHANGE_APP_IDLE_STATE, com.android.shell: android.permission.CHANGE_APP_IDLE_
STATE}

Bug: 63527785
Change-Id: I7a30615d20a6c22467a41d4b2d4f84f7702ce195